# Generated by Django 2.1.7 on 2019-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_de_chamados',
            fields=[
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_salt', models.CharField(max_length=100)),
                ('data_envio', models.CharField(default='2019-04-12', max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('hashtags', models.CharField(blank=True, max_length=20)),
                ('situacoes', models.CharField(max_length=50)),
                ('colaborador', models.CharField(max_length=50)),
            ],
        ),
    ]
